[engine]
evaluation_interval = 60
dry_run = false
policies_file = /etc/kronos/policies-evac.yaml
aggregates = test-agg
include_unassigned_hosts = false
cooldown = 600
instance_cooldown = 900
enforce_hard_affinity = false
enforce_soft_affinity = false
evacuate_disabled_hosts = true

[prometheus]
verify_ssl = false

[nova]
auth_type = password
auth_url = http://192.168.130.2:5000
username = admin
project_name = admin
user_domain_name = Default
project_domain_name = Default
